// --- Global Data Storage and Configuration ---
const users = {
    'user': 'user',     // Normal User
    'admin': 'admin'    // Admin
};

// Keys for localStorage
const DRAFT_STORAGE_KEY = 'kb_pending_drafts';
const EXPORT_LIST_KEY = 'kb_export_list';
const LOGIN_STATE_KEY = 'kb_login_state';
const UPLOADED_PDFS_KEY = 'kb_uploaded_pdfs';

let currentRole = null;
let currentLoggedInUser = null;

const oneYearInDays = 365;
let currentDraftId = null;
let exportList = [];
let uploadedPDFs = [];

// --- Helper function for adding articles to export list (defined early for global access) ---
window.addToExportListFromChecker = function() {
    if (!window.currentArticleData) {
        alert('No article data available. Please check an article first.');
        return;
    }
    
    const articleData = {
        title: window.currentArticleData.title,
        url: window.currentArticleData.url,
        lastUpdated: window.currentArticleData.lastUpdated,
        daysOld: window.currentArticleData.daysOld
    };
    
    // Check if article already exists
    const exists = exportList.find(item => 
        item.url === articleData.url || item.title === articleData.title
    );
    
    if (exists) {
        alert('This article is already in your export list!');
        return;
    }
    
    exportList.push({
        title: articleData.title,
        url: articleData.url,
        lastUpdated: articleData.lastUpdated,
        daysOld: articleData.daysOld,
        addedBy: currentLoggedInUser,
        addedAt: new Date().toISOString()
    });
    
    saveExportList(exportList);
    
    // Manually update UI elements
    const countSpan = document.getElementById('export-count');
    const container = document.getElementById('export-list-container');
    const exportBtn = document.getElementById('export-pdf-btn');
    const clearBtn = document.getElementById('clear-list-btn');
    
    if (countSpan) countSpan.textContent = exportList.length;
    
    if (container) {
        container.innerHTML = '';
        exportList.forEach((item, index) => {
            const itemDiv = document.createElement('div');
            itemDiv.className = 'export-item';
            itemDiv.innerHTML = `
                <div class="export-item-header">
                    <strong>${item.title}</strong>
                    <button class="remove-btn" onclick="removeFromExportList(${index})">Remove</button>
                </div>
                <p><strong>Last Updated:</strong> ${item.lastUpdated}</p>
                <p><strong>Age:</strong> ${(item.daysOld / 365.25).toFixed(1)} years (${item.daysOld} days)</p>
                <p><strong>URL:</strong> <a href="${item.url}" target="_blank">${item.url}</a></p>
            `;
            container.appendChild(itemDiv);
        });
    }
    
    if (exportBtn) exportBtn.disabled = false;
    if (clearBtn) clearBtn.disabled = false;
    
    alert(`"${articleData.title}" added to export list!`);
};

// --- Export List to PDF function (defined early for global access) ---
window.exportListToPDF = async function() {
    if (exportList.length === 0) {
        alert('Export list is empty!');
        return;
    }
    
    const exportBtn = document.getElementById('export-pdf-btn');
    if (exportBtn) {
        exportBtn.disabled = true;
        exportBtn.textContent = 'Generating PDF...';
    }
    
    try {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        
        // Add title
        doc.setFontSize(18);
        doc.setFont(undefined, 'bold');
        doc.text('VWO Outdated Articles - Export List', 20, 20);
        
        // Add metadata
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text(`Generated by: ${currentLoggedInUser}`, 20, 30);
        doc.text(`Date: ${new Date().toLocaleDateString('en-US')}`, 20, 35);
        doc.text(`Total Articles: ${exportList.length}`, 20, 40);
        
        // Add separator line
        doc.setLineWidth(0.5);
        doc.line(20, 45, 190, 45);
        
        let yPosition = 55;
        const pageHeight = doc.internal.pageSize.height;
        const marginBottom = 20;
        
        // Add articles
        exportList.forEach((item, index) => {
            // Check if we need a new page
            if (yPosition > pageHeight - marginBottom - 40) {
                doc.addPage();
                yPosition = 20;
            }
            
            // Article number and title
            doc.setFontSize(12);
            doc.setFont(undefined, 'bold');
            doc.text(`${index + 1}. ${item.title}`, 20, yPosition);
            yPosition += 7;
            
            // Details
            doc.setFontSize(10);
            doc.setFont(undefined, 'normal');
            doc.text(`Last Updated: ${item.lastUpdated}`, 25, yPosition);
            yPosition += 5;
            
            const yearsOld = (item.daysOld / 365.25).toFixed(1);
            doc.text(`Age: ${yearsOld} years (${item.daysOld} days)`, 25, yPosition);
            yPosition += 5;
            
            // URL (with text wrapping)
            doc.setTextColor(0, 0, 255);
            const urlLines = doc.splitTextToSize(`URL: ${item.url}`, 160);
            doc.text(urlLines, 25, yPosition);
            yPosition += urlLines.length * 5;
            doc.setTextColor(0, 0, 0);
            
            // Separator
            yPosition += 3;
            doc.setDrawColor(200, 200, 200);
            doc.line(20, yPosition, 190, yPosition);
            yPosition += 8;
        });
        
        // Save the PDF
        const filename = `VWO_Outdated_Articles_${currentLoggedInUser}_${new Date().getTime()}.pdf`;
        doc.save(filename);
        
        alert('PDF exported successfully!');
        
    } catch (error) {
        console.error('Error generating PDF:', error);
        alert('Error generating PDF. Please try again.');
    } finally {
        if (exportBtn) {
            exportBtn.disabled = false;
            exportBtn.textContent = '📄 Export to PDF';
        }
    }
};

// --- Remove from Export List function (defined early for global access) ---
window.removeFromExportList = function(index) {
    const item = exportList[index];
    if (confirm(`Remove "${item.title}" from export list?`)) {
        exportList.splice(index, 1);
        saveExportList(exportList);
        
        // Manually update UI
        const countSpan = document.getElementById('export-count');
        const container = document.getElementById('export-list-container');
        const exportBtn = document.getElementById('export-pdf-btn');
        const clearBtn = document.getElementById('clear-list-btn');
        
        if (countSpan) countSpan.textContent = exportList.length;
        
        if (exportList.length === 0) {
            if (container) container.innerHTML = '<p class="info">No articles in export list. Check outdated VWO articles above to start building your list.</p>';
            if (exportBtn) exportBtn.disabled = true;
            if (clearBtn) clearBtn.disabled = true;
        } else {
            if (container) {
                container.innerHTML = '';
                exportList.forEach((item, index) => {
                    const itemDiv = document.createElement('div');
                    itemDiv.className = 'export-item';
                    itemDiv.innerHTML = `
                        <div class="export-item-header">
                            <strong>${item.title}</strong>
                            <button class="remove-btn" onclick="removeFromExportList(${index})">Remove</button>
                        </div>
                        <p><strong>Last Updated:</strong> ${item.lastUpdated}</p>
                        <p><strong>Age:</strong> ${(item.daysOld / 365.25).toFixed(1)} years (${item.daysOld} days)</p>
                        <p><strong>URL:</strong> <a href="${item.url}" target="_blank">${item.url}</a></p>
                    `;
                    container.appendChild(itemDiv);
                });
            }
        }
    }
};

// --- Clear Export List function (defined early for global access) ---
window.clearExportList = function() {
    if (exportList.length === 0) return;
    
    if (confirm(`Clear all ${exportList.length} articles from export list?`)) {
        exportList = [];
        saveExportList(exportList);
        
        // Manually update UI
        const countSpan = document.getElementById('export-count');
        const container = document.getElementById('export-list-container');
        const exportBtn = document.getElementById('export-pdf-btn');
        const clearBtn = document.getElementById('clear-list-btn');
        
        if (countSpan) countSpan.textContent = '0';
        if (container) container.innerHTML = '<p class="info">No articles in export list. Check outdated VWO articles above to start building your list.</p>';
        if (exportBtn) exportBtn.disabled = true;
        if (clearBtn) clearBtn.disabled = true;
        
        alert('Export list cleared!');
    }
};

// --- Admin Functions (defined early for global access) ---

// Switch between admin tabs
window.switchTab = function(tabName) {
    const reviewsTab = document.getElementById('reviews-tab');
    const consolidateTab = document.getElementById('consolidate-tab');
    const reviewsBtn = document.querySelector('.tab-btn:nth-child(1)');
    const consolidateBtn = document.querySelector('.tab-btn:nth-child(2)');
    
    if (tabName === 'reviews') {
        if (reviewsTab) reviewsTab.style.display = 'block';
        if (consolidateTab) consolidateTab.style.display = 'none';
        if (reviewsBtn) reviewsBtn.classList.add('active');
        if (consolidateBtn) consolidateBtn.classList.remove('active');
    } else if (tabName === 'consolidate') {
        if (reviewsTab) reviewsTab.style.display = 'none';
        if (consolidateTab) consolidateTab.style.display = 'block';
        if (reviewsBtn) reviewsBtn.classList.remove('active');
        if (consolidateBtn) consolidateBtn.classList.add('active');
    }
};

// Upload PDFs
window.uploadPDFs = function() {
    const fileInput = document.getElementById('pdf-upload');
    const files = fileInput.files;
    
    if (files.length === 0) {
        alert('Please select at least one PDF file.');
        return;
    }
    
    // Process each file
    Array.from(files).forEach(file => {
        if (file.type !== 'application/pdf') {
            alert(`"${file.name}" is not a PDF file. Skipping.`);
            return;
        }
        
        const reader = new FileReader();
        reader.onload = function(e) {
            uploadedPDFs.push({
                name: file.name,
                uploadedAt: new Date().toISOString(),
                uploadedBy: currentLoggedInUser,
                size: file.size,
                base64: e.target.result
            });
            
            saveUploadedPDFs(uploadedPDFs);
            updateUploadedPDFsListManually();
        };
        reader.readAsDataURL(file);
    });
    
    // Clear file input
    fileInput.value = '';
};

// Update uploaded PDFs list manually
function updateUploadedPDFsListManually() {
    const container = document.getElementById('uploaded-pdfs-list');
    const consolidateBtn = document.getElementById('consolidate-btn');
    
    if (!container) return;
    
    if (uploadedPDFs.length === 0) {
        container.innerHTML = '<p class="info">No PDFs uploaded yet.</p>';
        if (consolidateBtn) consolidateBtn.disabled = true;
    } else {
        if (consolidateBtn) consolidateBtn.disabled = false;
        
        container.innerHTML = '';
        uploadedPDFs.forEach((pdf, index) => {
            const item = document.createElement('div');
            item.className = 'pdf-list-item';
            const sizeKB = (pdf.size / 1024).toFixed(2);
            item.innerHTML = `
                <span>📄 ${pdf.name} (${sizeKB} KB)</span>
                <button onclick="removeUploadedPDF(${index})">Remove</button>
            `;
            container.appendChild(item);
        });
    }
}

// Remove uploaded PDF
window.removeUploadedPDF = function(index) {
    if (confirm('Remove this PDF?')) {
        uploadedPDFs.splice(index, 1);
        saveUploadedPDFs(uploadedPDFs);
        updateUploadedPDFsListManually();
    }
};

// Consolidate PDFs
window.consolidatePDFs = async function() {
    if (uploadedPDFs.length === 0) {
        alert('No PDFs to consolidate!');
        return;
    }
    
    const consolidateBtn = document.getElementById('consolidate-btn');
    const resultDiv = document.getElementById('consolidation-result');
    
    consolidateBtn.disabled = true;
    consolidateBtn.textContent = '🔄 Processing PDFs...';
    resultDiv.innerHTML = '<p class="info">Extracting article data from uploaded PDFs...</p>';
    
    try {
        const allArticles = [];
        const articleFrequency = new Map();
        
        // Extract text from each PDF
        for (const pdfData of uploadedPDFs) {
            const articles = await extractArticlesFromPDF(pdfData);
            articles.forEach(article => {
                allArticles.push({
                    ...article,
                    source: pdfData.name
                });
                
                // Track frequency
                const key = article.url || article.title;
                if (articleFrequency.has(key)) {
                    const existing = articleFrequency.get(key);
                    existing.count++;
                    existing.sources.push(pdfData.name);
                } else {
                    articleFrequency.set(key, {
                        article: article,
                        count: 1,
                        sources: [pdfData.name]
                    });
                }
            });
        }
        
        // Sort by frequency (priority)
        const sortedArticles = Array.from(articleFrequency.values())
            .sort((a, b) => b.count - a.count);
        
        // Generate consolidated report
        await generateConsolidatedReport(sortedArticles, uploadedPDFs.length);
        
        resultDiv.innerHTML = `
            <div class="current">
                <h4>✅ Consolidation Complete!</h4>
                <p><strong>Total PDFs processed:</strong> ${uploadedPDFs.length}</p>
                <p><strong>Unique articles found:</strong> ${sortedArticles.length}</p>
                <p><strong>High-priority articles:</strong> ${sortedArticles.filter(a => a.count > 1).length} (appeared in multiple lists)</p>
                <p>📄 Consolidated report has been downloaded.</p>
            </div>
        `;
        
    } catch (error) {
        console.error('Error consolidating PDFs:', error);
        resultDiv.innerHTML = `
            <div class="error">
                <h4>❌ Error Processing PDFs</h4>
                <p>${error.message}</p>
                <p>Please ensure all uploaded files are valid PDFs.</p>
            </div>
        `;
    } finally {
        consolidateBtn.disabled = false;
        consolidateBtn.textContent = '🔗 Consolidate & Generate Report';
    }
};

// Extract articles from PDF (defined early for global access)
async function extractArticlesFromPDF(pdfData) {
    const pdfjsLib = window['pdfjs-dist/build/pdf'];
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
    
    // Convert base64 to Uint8Array
    const base64Data = pdfData.base64.split(',')[1];
    const binaryString = atob(base64Data);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    
    const pdf = await pdfjsLib.getDocument({ data: bytes }).promise;
    let fullText = '';
    
    // Extract text from all pages
    for (let i = 1; i <= pdf.numPages; i++) {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();
        const pageText = textContent.items.map(item => item.str).join(' ');
        fullText += pageText + '\n';
    }
    
    // Parse articles from text
    const articles = parseArticlesFromText(fullText);
    return articles;
}

// Parse articles from extracted PDF text
function parseArticlesFromText(text) {
    const articles = [];
    
    // Pattern 1: Look for numbered items with URLs
    const pattern1 = /(\d+)\.\s+([^\n]+?)\s+Last Updated:\s+([^\n]+?)\s+Age:\s+([^\n]+?)\s+URL:\s+(https?:\/\/[^\s\n]+)/gi;
    let match;
    
    while ((match = pattern1.exec(text)) !== null) {
        articles.push({
            title: match[2].trim(),
            lastUpdated: match[3].trim(),
            age: match[4].trim(),
            url: match[5].trim()
        });
    }
    
    // Pattern 2: Alternative format without numbering
    const pattern2 = /([^\n]+?)\s+Last Updated:\s+([^\n]+?)\s+Age:\s+([^\n]+?)\s+URL:\s+(https?:\/\/[^\s\n]+)/gi;
    while ((match = pattern2.exec(text)) !== null) {
        const title = match[1].trim();
        if (!articles.find(a => a.title === title)) {
            articles.push({
                title: title,
                lastUpdated: match[2].trim(),
                age: match[3].trim(),
                url: match[4].trim()
            });
        }
    }
    
    return articles;
}

// Generate consolidated PDF report
async function generateConsolidatedReport(sortedArticles, totalPDFs) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('VWO Articles - Consolidated Priority Report', 20, 20);
    
    // Add metadata
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Generated by: ${currentLoggedInUser}`, 20, 30);
    doc.text(`Date: ${new Date().toLocaleDateString('en-US')}`, 20, 35);
    doc.text(`PDFs Consolidated: ${totalPDFs}`, 20, 40);
    doc.text(`Unique Articles: ${sortedArticles.length}`, 20, 45);
    
    // Add separator line
    doc.setLineWidth(0.5);
    doc.line(20, 50, 190, 50);
    
    let yPosition = 60;
    const pageHeight = doc.internal.pageSize.height;
    const marginBottom = 20;
    
    // Add articles sorted by priority
    sortedArticles.forEach((item, index) => {
        const article = item.article;
        
        // Check if we need a new page
        if (yPosition > pageHeight - marginBottom - 50) {
            doc.addPage();
            yPosition = 20;
        }
        
        // Priority badge
        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        const priorityText = item.count > 1 ? `🔥 PRIORITY ${item.count}x` : `${index + 1}.`;
        doc.text(priorityText, 20, yPosition);
        yPosition += 7;
        
        // Article title
        doc.setFontSize(11);
        const titleLines = doc.splitTextToSize(article.title, 160);
        doc.text(titleLines, 25, yPosition);
        yPosition += titleLines.length * 6;
        
        // Details
        doc.setFontSize(9);
        doc.setFont(undefined, 'normal');
        doc.text(`Last Updated: ${article.lastUpdated || 'Unknown'}`, 25, yPosition);
        yPosition += 5;
        doc.text(`Age: ${article.age || 'Unknown'}`, 25, yPosition);
        yPosition += 5;
        
        // Sources (if multiple)
        if (item.count > 1) {
            doc.text(`Found in: ${item.sources.join(', ')}`, 25, yPosition);
            yPosition += 5;
        }
        
        // URL
        doc.setTextColor(0, 0, 255);
        const urlLines = doc.splitTextToSize(`URL: ${article.url}`, 160);
        doc.text(urlLines, 25, yPosition);
        yPosition += urlLines.length * 5;
        doc.setTextColor(0, 0, 0);
        
        // Separator
        yPosition += 3;
        doc.setDrawColor(200, 200, 200);
        doc.line(20, yPosition, 190, yPosition);
        yPosition += 8;
    });
    
    // Save the PDF
    const filename = `VWO_Consolidated_Report_${new Date().getTime()}.pdf`;
    doc.save(filename);
}

// --- Data Initialization and Persistence Functions ---

function loadDrafts() {
    const storedDrafts = localStorage.getItem(DRAFT_STORAGE_KEY);
    return storedDrafts ? JSON.parse(storedDrafts) : [];
}

function saveDrafts(drafts) {
    localStorage.setItem(DRAFT_STORAGE_KEY, JSON.stringify(drafts));
}

function loadExportList() {
    const storedList = localStorage.getItem(EXPORT_LIST_KEY);
    return storedList ? JSON.parse(storedList) : [];
}

function saveExportList(list) {
    localStorage.setItem(EXPORT_LIST_KEY, JSON.stringify(list));
}

function loadUploadedPDFs() {
    const storedPDFs = localStorage.getItem(UPLOADED_PDFS_KEY);
    return storedPDFs ? JSON.parse(storedPDFs) : [];
}

function saveUploadedPDFs(pdfs) {
    localStorage.setItem(UPLOADED_PDFS_KEY, JSON.stringify(pdfs));
}

// Global variable for drafts, loaded on script start
let pendingDrafts = loadDrafts();


// --- DOM Elements ---
const loginScreen = document.getElementById('login-screen');
const checkerView = document.getElementById('checker-view');
const reviewerView = document.getElementById('reviewer-view');
const pendingDraftsContainer = document.getElementById('pending-drafts');
const currentUsernameSpan = document.getElementById('current-username');
const currentAdminSpan = document.getElementById('current-admin');


// --- NEW: VWO Article URL Checker Functions ---

async function checkVWOArticle() {
    const urlInput = document.getElementById('vwo-article-url');
    const resultDiv = document.getElementById('vwo-result');
    const checkBtn = document.getElementById('check-vwo-btn');
    
    const url = urlInput.value.trim();
    
    // Validate URL
    if (!url) {
        resultDiv.innerHTML = '<p class="error">⚠️ Please enter a VWO article URL</p>';
        return;
    }
    
    if (!url.includes('help.vwo.com')) {
        resultDiv.innerHTML = '<p class="error">⚠️ Please enter a valid VWO help article URL (must contain "help.vwo.com")</p>';
        return;
    }
    
    // Show loading state
    checkBtn.disabled = true;
    checkBtn.textContent = 'Checking...';
    resultDiv.innerHTML = '<p class="info">🔄 Fetching article data...</p>';
    
    try {
        // Try multiple CORS proxies as fallback
        const corsProxies = [
            'https://api.allorigins.win/raw?url=',
            'https://corsproxy.io/?',
            'https://api.codetabs.com/v1/proxy?quest='
        ];
        
        let html = null;
        let lastError = null;
        
        // Try each proxy until one works
        for (const corsProxy of corsProxies) {
            try {
                const proxyUrl = corsProxy + encodeURIComponent(url);
                console.log('Trying proxy:', corsProxy);
                
                const response = await fetch(proxyUrl, { 
                    method: 'GET',
                    headers: {
                        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
                    }
                });
                
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                
                html = await response.text();
                console.log('Successfully fetched with proxy:', corsProxy);
                break; // Success! Exit the loop
                
            } catch (proxyError) {
                console.warn('Proxy failed:', corsProxy, proxyError.message);
                lastError = proxyError;
                continue; // Try next proxy
            }
        }
        
        // If all proxies failed, throw the last error
        if (!html) {
            throw new Error(`All CORS proxies failed. Last error: ${lastError?.message || 'Unknown error'}`);
        }
        
        console.log('Fetched HTML length:', html.length);
        console.log('Checking if HTML contains <time> tag:', html.includes('<time'));
        console.log('Checking if HTML contains datetime:', html.includes('datetime'));
        
        // Extract the update date from the HTML
        const updateDate = extractUpdateDate(html);
        
        if (!updateDate) {
            // Show a sample of the HTML for debugging
            const htmlSample = html.substring(0, 1000);
            console.log('HTML Sample (first 1000 chars):', htmlSample);
            
            // Also search for any time-related content
            const timeTagSearch = html.match(/<time[^>]*>.*?<\/time>/gi);
            if (timeTagSearch) {
                console.log('Found <time> tags:', timeTagSearch);
            }
            
            resultDiv.innerHTML = `
                <div class="error">
                    <h4>❌ Could not find the update date</h4>
                    <p>The date extraction patterns didn't match the article's HTML structure.</p>
                    <p><strong>Debug Info:</strong></p>
                    <ul>
                        <li>Article was fetched successfully</li>
                        <li>HTML length: ${html.length} characters</li>
                        <li>Contains &lt;time&gt; tag: ${html.includes('<time') ? 'Yes' : 'No'}</li>
                        <li>Contains "datetime": ${html.includes('datetime') ? 'Yes' : 'No'}</li>
                        <li>Check browser console (F12) for more details</li>
                    </ul>
                    <p><strong>Possible causes:</strong></p>
                    <ul>
                        <li>VWO changed their article HTML structure</li>
                        <li>This might not be a standard help article page</li>
                    </ul>
                    <p><a href="${url}" target="_blank">Open article in new tab to check manually</a></p>
                </div>
            `;
            return;
        }
        
        console.log('Extracted date string:', updateDate);
        
        // Calculate age of the article
        const articleDate = new Date(updateDate);
        
        // Check if date is valid
        if (isNaN(articleDate.getTime())) {
            resultDiv.innerHTML = `
                <div class="error">
                    <h4>❌ Invalid date format</h4>
                    <p><strong>Found date string:</strong> "${updateDate}"</p>
                    <p>This date format couldn't be parsed by JavaScript's Date parser.</p>
                    <p><a href="${url}" target="_blank">Open article to check the date manually</a></p>
                </div>
            `;
            return;
        }
        
        const currentDate = new Date();
        const timeDifference = currentDate.getTime() - articleDate.getTime();
        const daysDifference = timeDifference / (1000 * 3600 * 24);
        
        // Format the date nicely
        const formattedDate = articleDate.toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
        });
        
        console.log('Parsed date:', formattedDate, 'Age:', daysDifference, 'days');
        
        // Check if article is outdated (more than 1 year)
        if (daysDifference > oneYearInDays) {
            const daysAgo = Math.floor(daysDifference);
            const yearsAgo = (daysAgo / 365.25).toFixed(1);
            const monthsAgo = Math.floor(daysDifference / 30);
            
            // Extract article title from URL or use URL as fallback
            const articleTitle = extractArticleTitle(url);
            
            // Check if already submitted
            pendingDrafts = loadDrafts();
            const existingDraft = pendingDrafts.find(d => d.title === articleTitle && d.isVWOArticle);
            
            if (existingDraft) {
                // Store article data globally for the button click
                window.currentArticleData = {
                    url: url,
                    title: articleTitle,
                    lastUpdated: formattedDate,
                    daysOld: daysAgo
                };
                
                resultDiv.innerHTML = `
                    <div class="outdated">
                        <h4>🚨 ARTICLE OUTDATED</h4>
                        <p><strong>Article:</strong> ${articleTitle}</p>
                        <p><strong>Last Updated:</strong> ${formattedDate}</p>
                        <p><strong>Age:</strong> ${yearsAgo} years old (${daysAgo} days / ${monthsAgo} months)</p>
                        <p>⚠️ This article needs to be reviewed and updated!</p>
                        <hr>
                        <p class="info">✓ This article has already been submitted for review.</p>
                        <button onclick="addToExportListFromChecker()">📋 Add to Export List</button>
                    </div>
                `;
            } else {
                // Store article data globally for the button click
                window.currentArticleData = {
                    url: url,
                    title: articleTitle,
                    lastUpdated: formattedDate,
                    daysOld: daysAgo
                };
                
                resultDiv.innerHTML = `
                    <div class="outdated">
                        <h4>🚨 ARTICLE OUTDATED</h4>
                        <p><strong>Article:</strong> ${articleTitle}</p>
                        <p><strong>Last Updated:</strong> ${formattedDate}</p>
                        <p><strong>Age:</strong> ${yearsAgo} years old (${daysAgo} days / ${monthsAgo} months)</p>
                        <p>⚠️ This article needs to be reviewed and updated!</p>
                        <p><strong>URL:</strong> <a href="${url}" target="_blank">${url}</a></p>
                        <hr>
                        <h4>📝 Submit for Review</h4>
                        <p>Flag this outdated VWO article for the review team:</p>
                        <textarea id="vwo-notes" rows="4" placeholder="Optional: Add notes about what needs updating (e.g., 'Screenshots are outdated', 'New features not documented', etc.)"></textarea>
                        <button onclick="submitVWOForReview('${url}', '${articleTitle}', '${formattedDate}', ${daysAgo})">Submit Article for Review</button>
                        <button onclick="addToExportListFromChecker()" style="margin-left: 10px;">📋 Add to Export List</button>
                    </div>
                `;
            }
        } else {
            const daysAgo = Math.floor(daysDifference);
            const monthsAgo = Math.floor(daysDifference / 30);
            const articleTitle = extractArticleTitle(url);
            
            resultDiv.innerHTML = `
                <div class="current">
                    <h4>✅ ARTICLE UP-TO-DATE</h4>
                    <p><strong>Article:</strong> ${articleTitle}</p>
                    <p><strong>Last Updated:</strong> ${formattedDate}</p>
                    <p><strong>Age:</strong> ${daysAgo} days old (${monthsAgo} months)</p>
                    <p>✓ This article has been updated within the last year.</p>
                    <button onclick="addToExportListFromChecker('${url.replace(/'/g, "\\'")}', '${articleTitle.replace(/'/g, "\\'")}', '${formattedDate}', ${daysAgo})">📋 Add to Export List</button>
                </div>
            `;
        }
        
    } catch (error) {
        console.error('Error fetching VWO article:', error);
        resultDiv.innerHTML = `
            <div class="error">
                <h4>❌ Error Checking Article</h4>
                <p><strong>Error:</strong> ${error.message}</p>
                <p><strong>Note:</strong> This app now uses a CORS proxy (AllOrigins) to bypass browser restrictions.</p>
                <p>If you still see this error, it could be due to:</p>
                <ul>
                    <li>Network connectivity issues</li>
                    <li>Invalid or inaccessible URL</li>
                    <li>CORS proxy service temporarily unavailable</li>
                </ul>
                <p><strong>Alternative Solutions:</strong></p>
                <ul>
                    <li>Install browser extension: "Allow CORS: Access-Control-Allow-Origin" for Chrome</li>
                    <li>Try again in a few moments (proxy might be slow)</li>
                    <li>Check the article directly at: <a href="${url}" target="_blank">Open Article</a></li>
                </ul>
            </div>
        `;
    } finally {
        // Reset button state
        checkBtn.disabled = false;
        checkBtn.textContent = 'Check Article';
    }
}

function extractUpdateDate(html) {
    // VWO help articles show update date in multiple possible locations
    // Let's try all patterns and log what we find for debugging
    
    console.log('Searching for date in HTML...');
    console.log('HTML length:', html.length);
    
    // Pattern 1: Look for <time> tag with datetime attribute (EXACT VWO format)
    // Example: <time datetime="2025-08-04T14:51:23Z" title="08/04/2025, 08:51" data-datetime="relative">
    // IMPORTANT: Match datetime but NOT data-datetime
    const timeMatch = html.match(/<time[^>]*\sdatetime=["']([^"']+)["']/i);
    if (timeMatch && timeMatch[1] !== 'relative') {
        console.log('Found date via <time> tag:', timeMatch[1]);
        return timeMatch[1];
    }
    
    // Pattern 1b: Look specifically for ISO date format in datetime attribute
    // This will match: datetime="2025-08-04T14:51:23Z" but skip datetime="relative"
    const isoDatetimeMatch = html.match(/\sdatetime=["'](\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z?)["']/i);
    if (isoDatetimeMatch) {
        console.log('Found ISO date via datetime attribute:', isoDatetimeMatch[1]);
        return isoDatetimeMatch[1];
    }
    
    // Pattern 2: Look for data-datetime attribute
    const dataTimeMatch = html.match(/data-datetime=["']([^"']+)["']/i);
    if (dataTimeMatch) {
        console.log('Found date via data-datetime:', dataTimeMatch[1]);
        return dataTimeMatch[1];
    }
    
    // Pattern 3: Look for meta tag with article:modified_time
    const metaMatch = html.match(/<meta[^>]*property=["']article:modified_time["'][^>]*content=["']([^"']+)["']/i);
    if (metaMatch) {
        console.log('Found date via meta tag:', metaMatch[1]);
        return metaMatch[1];
    }
    
    // Pattern 4: Look for Zendesk specific datetime format
    const zendeskMatch = html.match(/datetime=["'](\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z)["']/i);
    if (zendeskMatch) {
        console.log('Found date via Zendesk format:', zendeskMatch[1]);
        return zendeskMatch[1];
    }
    
    // Pattern 5: Look for "Updated" text followed by a date (various formats)
    const updatedMatch = html.match(/(?:Updated|Last updated|Modified|Edited)[\s:]+([A-Za-z]+\s+\d{1,2},?\s+\d{4})/i);
    if (updatedMatch) {
        console.log('Found date via "Updated" text:', updatedMatch[1]);
        return updatedMatch[1];
    }
    
    // Pattern 6: Look for any ISO date format in the HTML
    const isoMatch = html.match(/(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})/);
    if (isoMatch) {
        console.log('Found date via ISO format:', isoMatch[1]);
        return isoMatch[1];
    }
    
    // Pattern 7: Look for "article-updated-at" or similar class/id attributes
    const articleUpdatedMatch = html.match(/(?:article-updated-at|updated-at|last-modified)[^>]*>([^<]+)</i);
    if (articleUpdatedMatch) {
        console.log('Found date via article-updated class:', articleUpdatedMatch[1]);
        return articleUpdatedMatch[1].trim();
    }
    
    console.log('No date found in HTML');
    return null;
}

// Helper function to extract article title from URL
function extractArticleTitle(url) {
    // VWO URLs format: https://help.vwo.com/hc/en-us/articles/360019419534-What-is-VWO-Experience-Optimization-Platform
    // Extract the title part after the article ID
    const match = url.match(/articles\/\d+-(.+)/);
    if (match) {
        // Convert hyphens to spaces and capitalize
        return match[1]
            .split('-')
            .map(word => word.charAt(0).toUpperCase() + word.slice(1))
            .join(' ');
    }
    // Fallback to URL if can't extract title
    return url;
}

// Submit VWO article for review
function submitVWOForReview(url, title, lastUpdated, daysOld) {
    const notes = document.getElementById('vwo-notes').value.trim();
    
    const draft = {
        id: Date.now(),
        title: title,
        content: `VWO Article flagged for update:

URL: ${url}
Last Updated: ${lastUpdated}
Age: ${daysOld} days old

User Notes:
${notes || 'No additional notes provided.'}

Action Required:
This VWO help article needs to be reviewed and updated to reflect current product features and UI.`,
        submittedBy: currentLoggedInUser,
        originalDate: lastUpdated,
        status: 'pending',
        isVWOArticle: true,
        articleURL: url
    };
    
    pendingDrafts.push(draft);
    saveDrafts(pendingDrafts);
    
    alert(`VWO Article "${title}" has been flagged for review!\n\nThe admin team will be notified.`);
    
    // Refresh the result to show "already submitted" message
    checkVWOArticle();
}


// --- 1. Authentication Functions ---

function loginUser() {
    const usernameInput = document.getElementById('username').value;
    const passwordInput = document.getElementById('password').value;
    const errorMsg = document.getElementById('login-error');
    errorMsg.textContent = '';

    if (users[usernameInput] === passwordInput) {
        const loginState = { 
            user: usernameInput, 
            role: usernameInput === 'admin' ? 'reviewer' : 'user' 
        };
        localStorage.setItem(LOGIN_STATE_KEY, JSON.stringify(loginState));

        currentLoggedInUser = loginState.user;
        currentRole = loginState.role;
        loginScreen.style.display = 'none';

        if (currentRole === 'reviewer') {
            showReviewerView();
        } else {
            showCheckerView();
        }
    } else {
        errorMsg.textContent = 'Invalid username or password.';
    }
}

function logoutUser() {
    localStorage.removeItem(LOGIN_STATE_KEY);
    currentLoggedInUser = null;
    currentRole = null;
    
    // Show only the login screen
    checkerView.style.display = 'none';
    reviewerView.style.display = 'none';
    loginScreen.style.display = 'block';

    document.getElementById('username').value = '';
    document.getElementById('password').value = '';
}

function showCheckerView() {
    currentUsernameSpan.textContent = currentLoggedInUser;
    checkerView.style.display = 'block';
    reviewerView.style.display = 'none';
    // Export list is already initialized by initializeExportList() in DOMContentLoaded
}

function showReviewerView() {
    currentAdminSpan.textContent = currentLoggedInUser;
    reviewerView.style.display = 'block';
    checkerView.style.display = 'none';
    updateReviewPanel();
}


// --- 2. Article Checker Logic (User View) ---
// --- 3. Peer Review Logic (Admin View) ---

function updateReviewPanel() {
    if (currentRole !== 'reviewer') return;

    pendingDraftsContainer.innerHTML = '';
    
    pendingDrafts = loadDrafts(); 
    
    if (pendingDrafts.length === 0) {
        pendingDraftsContainer.innerHTML = '<p class="info">No pending drafts for peer review at this time.</p>';
        return;
    }

    pendingDrafts.forEach(draft => {
        const item = document.createElement('div');
        item.className = 'draft-item';
        
        // Different styling for VWO articles
        if (draft.isVWOArticle) {
            item.innerHTML = `
                <span>
                    <strong>🌐 VWO Article:</strong> ${draft.title}<br>
                    <small>Submitted by: ${draft.submittedBy} | <a href="${draft.articleURL}" target="_blank">View Article</a></small>
                </span>
                <button onclick="openModal(${draft.id})">Review Flag</button>
            `;
            item.style.backgroundColor = '#d1ecf1'; // Light blue for VWO articles
        } else {
            item.innerHTML = `
                <span>Draft for: <strong>${draft.title}</strong> (Submitted by: ${draft.submittedBy})</span>
                <button onclick="openModal(${draft.id})">Review Draft</button>
            `;
        }
        
        pendingDraftsContainer.appendChild(item);
    });
}

function openModal(draftId) {
    const draft = pendingDrafts.find(d => d.id === draftId);
    if (!draft) return;

    currentDraftId = draftId;

    document.getElementById('draft-title').textContent = draft.title;
    document.getElementById('draft-submitter').textContent = draft.submittedBy;
    document.getElementById('draft-original-date').textContent = draft.originalDate;
    document.getElementById('draft-review-content').value = draft.content;
    
    // Show different message for VWO articles
    if (draft.isVWOArticle) {
        document.getElementById('review-status-message').textContent = 'Review this VWO article flag and decide if it needs updating...';
    } else {
        document.getElementById('review-status-message').textContent = 'Awaiting your decision...';
    }
    document.getElementById('review-status-message').className = 'info';

    document.getElementById('draft-modal').style.display = 'block';
}

function closeModal() {
    document.getElementById('draft-modal').style.display = 'none';
    currentDraftId = null;
}

function reviewAction(action) {
    const draftIndex = pendingDrafts.findIndex(d => d.id === currentDraftId);
    if (draftIndex === -1) return;

    const messageElement = document.getElementById('review-status-message');
    const draft = pendingDrafts[draftIndex];
    const draftTitle = draft.title;

    if (action === 'approve') {
        if (draft.isVWOArticle) {
            // For VWO articles, acknowledge the flag
            pendingDrafts.splice(draftIndex, 1);
            saveDrafts(pendingDrafts);
            
            messageElement.textContent = `✅ VWO Article Acknowledged! Article "${draftTitle}" has been flagged for the documentation team to update.`;
            messageElement.className = 'current';
    } else if (action === 'reject') {
        // Remove draft
        pendingDrafts.splice(draftIndex, 1);
        saveDrafts(pendingDrafts); 
        
        messageElement.textContent = `❌ VWO Article flag dismissed. No action will be taken.`;
        messageElement.className = 'outdated';
    }

    // Refresh the panel and close the modal after a short delay
    setTimeout(() => {
        closeModal();
        updateReviewPanel();
    }, 1500);
}


// --- 4. Initialization and Auto-Login Check ---

function checkInitialLogin() {
    const storedState = localStorage.getItem(LOGIN_STATE_KEY);
    
    // Ensure all views are hidden first, then display the correct one
    loginScreen.style.display = 'none';
    checkerView.style.display = 'none';
    reviewerView.style.display = 'none';
    
    if (storedState) {
        const state = JSON.parse(storedState);
        currentLoggedInUser = state.user;
        currentRole = state.role;

        if (currentRole === 'reviewer') {
            showReviewerView();
        } else {
            showCheckerView();
        }
    } else {
        // Show only the login screen if no stored state is found
        loginScreen.style.display = 'block';
    }
}

// Allow closing the modal by clicking outside of it
window.onclick = function(event) {
    const modal = document.getElementById('draft-modal');
    if (event.target === modal) {
        closeModal();
    }
}

// --- DOM Elements ---
const loginScreen = document.getElementById('login-screen');
const checkerView = document.getElementById('checker-view');
const reviewerView = document.getElementById('reviewer-view');
const pendingDraftsContainer = document.getElementById('pending-drafts');
const currentUsernameSpan = document.getElementById('current-username');
const currentAdminSpan = document.getElementById('current-admin');


// --- 5. Export List Functions ---

// Initialize export list on page load
function initializeExportList() {
    exportList = loadExportList();
    updateExportListUI();
}

// Add article to export list
function addToExportList(articleData) {
    // Check if article already exists
    const exists = exportList.find(item => 
        item.url === articleData.url || item.title === articleData.title
    );
    
    if (exists) {
        alert('This article is already in your export list!');
        return;
    }
    
    exportList.push({
        title: articleData.title,
        url: articleData.url,
        lastUpdated: articleData.lastUpdated,
        daysOld: articleData.daysOld,
        addedBy: currentLoggedInUser,
        addedAt: new Date().toISOString()
    });
    
    saveExportList(exportList);
    updateExportListUI();
    
    alert(`"${articleData.title}" added to export list!`);
}

// Update export list UI
function updateExportListUI() {
    const countSpan = document.getElementById('export-count');
    const container = document.getElementById('export-list-container');
    const exportBtn = document.getElementById('export-pdf-btn');
    const clearBtn = document.getElementById('clear-list-btn');
    
    countSpan.textContent = exportList.length;
    
    if (exportList.length === 0) {
        container.innerHTML = '<p class="info">No articles in export list. Check outdated VWO articles above to start building your list.</p>';
        exportBtn.disabled = true;
        clearBtn.disabled = true;
    } else {
        exportBtn.disabled = false;
        clearBtn.disabled = true;
        
        let html = '<div class="export-items">';
        exportList.forEach((item, index) => {
            const yearsOld = (item.daysOld / 365.25).toFixed(1);
            html += `
                <div class="export-item">
                    <div class="export-item-header">
                        <strong>${index + 1}. ${item.title}</strong>
                        <button class="remove-btn" onclick="removeFromExportList(${index})">✕</button>
                    </div>
                    <div class="export-item-details">
                        <p><strong>Last Updated:</strong> ${item.lastUpdated}</p>
                        <p><strong>Age:</strong> ${yearsOld} years (${item.daysOld} days)</p>
                        <p><strong>URL:</strong> <a href="${item.url}" target="_blank">${item.url}</a></p>
                    </div>
                </div>
            `;
        });
        html += '</div>';
        container.innerHTML = html;
    }
}

// Remove item from export list
function removeFromExportList(index) {
    const item = exportList[index];
    if (confirm(`Remove "${item.title}" from export list?`)) {
        exportList.splice(index, 1);
        saveExportList(exportList);
        updateExportListUI();
    }
}

// Make function globally accessible
window.removeFromExportList = removeFromExportList;

// Clear entire export list
function clearExportList() {
    if (exportList.length === 0) return;
    
    if (confirm(`Clear all ${exportList.length} articles from export list?`)) {
        exportList = [];
        saveExportList(exportList);
        updateExportListUI();
        alert('Export list cleared!');
    }
}

// Make function globally accessible
window.clearExportList = clearExportList;

// Export list to PDF
async function exportListToPDF() {
    if (exportList.length === 0) {
        alert('Export list is empty!');
        return;
    }
    
    const exportBtn = document.getElementById('export-pdf-btn');
    exportBtn.disabled = true;
    exportBtn.textContent = 'Generating PDF...';
    
    try {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        
        // Add title
        doc.setFontSize(18);
        doc.setFont(undefined, 'bold');
        doc.text('VWO Outdated Articles - Export List', 20, 20);
        
        // Add metadata
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text(`Generated by: ${currentLoggedInUser}`, 20, 30);
        doc.text(`Date: ${new Date().toLocaleDateString('en-US')}`, 20, 35);
        doc.text(`Total Articles: ${exportList.length}`, 20, 40);
        
        // Add separator line
        doc.setLineWidth(0.5);
        doc.line(20, 45, 190, 45);
        
        let yPosition = 55;
        const pageHeight = doc.internal.pageSize.height;
        const marginBottom = 20;
        
        // Add articles
        exportList.forEach((item, index) => {
            // Check if we need a new page
            if (yPosition > pageHeight - marginBottom - 40) {
                doc.addPage();
                yPosition = 20;
            }
            
            // Article number and title
            doc.setFontSize(12);
            doc.setFont(undefined, 'bold');
            doc.text(`${index + 1}. ${item.title}`, 20, yPosition);
            yPosition += 7;
            
            // Details
            doc.setFontSize(10);
            doc.setFont(undefined, 'normal');
            doc.text(`Last Updated: ${item.lastUpdated}`, 25, yPosition);
            yPosition += 5;
            
            const yearsOld = (item.daysOld / 365.25).toFixed(1);
            doc.text(`Age: ${yearsOld} years (${item.daysOld} days)`, 25, yPosition);
            yPosition += 5;
            
            // URL (with text wrapping)
            doc.setTextColor(0, 0, 255);
            const urlLines = doc.splitTextToSize(`URL: ${item.url}`, 160);
            doc.text(urlLines, 25, yPosition);
            yPosition += urlLines.length * 5;
            doc.setTextColor(0, 0, 0);
            
            // Separator
            yPosition += 3;
            doc.setDrawColor(200, 200, 200);
            doc.line(20, yPosition, 190, yPosition);
            yPosition += 8;
        });
        
        // Save the PDF
        const filename = `VWO_Outdated_Articles_${currentLoggedInUser}_${new Date().getTime()}.pdf`;
        doc.save(filename);
        
        // Auto-clear after export
        if (confirm('PDF exported successfully! Clear the export list?')) {
            clearExportList();
        }
        
    } catch (error) {
        console.error('Error generating PDF:', error);
        alert('Error generating PDF. Please try again.');
    } finally {
        exportBtn.disabled = false;
        exportBtn.textContent = '📄 Export to PDF';
    }
}

// Make function globally accessible
window.exportListToPDF = exportListToPDF;

// Modify the submitVWOForReview function to add option to export list
// This creates a new version that includes adding to export list
function submitVWOForReview(url, title, lastUpdated, daysOld) {
    const notes = document.getElementById('vwo-notes').value.trim();
    
    // Add to export list
    const articleData = {
        title: title,
        url: url,
        lastUpdated: lastUpdated,
        daysOld: daysOld
    };
    addToExportList(articleData);
    
    // Also submit for review as before
    const draft = {
        id: Date.now(),
        title: title,
        content: `VWO Article flagged for update:

URL: ${url}
Last Updated: ${lastUpdated}
Age: ${daysOld} days old

User Notes:
${notes || 'No additional notes provided.'}

Action Required:
This VWO help article needs to be reviewed and updated to reflect current product features and UI.`,
        submittedBy: currentLoggedInUser,
        originalDate: lastUpdated,
        status: 'pending',
        isVWOArticle: true,
        articleURL: url
    };
    
    pendingDrafts.push(draft);
    saveDrafts(pendingDrafts);
    
    alert(`✅ Article "${title}" has been:\n• Added to your export list\n• Flagged for admin review`);
    
    // Refresh the result to show "already submitted" message
    checkVWOArticle();
}


// --- 6. Admin PDF Consolidation Functions ---

// Switch admin tabs
function switchTab(tabName) {
    const reviewsTab = document.getElementById('reviews-tab');
    const consolidateTab = document.getElementById('consolidate-tab');
    const tabButtons = document.querySelectorAll('.tab-btn');
    
    if (tabName === 'reviews') {
        reviewsTab.style.display = 'block';
        consolidateTab.style.display = 'none';
        tabButtons[0].classList.add('active');
        tabButtons[1].classList.remove('active');
    } else if (tabName === 'consolidate') {
        reviewsTab.style.display = 'none';
        consolidateTab.style.display = 'block';
        tabButtons[0].classList.remove('active');
        tabButtons[1].classList.add('active');
        updateUploadedPDFsList();
    }
}

// Upload PDFs
function uploadPDFs() {
    const fileInput = document.getElementById('pdf-upload');
    const files = fileInput.files;
    
    if (files.length === 0) {
        alert('Please select PDF files to upload.');
        return;
    }
    
    Array.from(files).forEach(file => {
        if (file.type !== 'application/pdf') {
            alert(`Skipping "${file.name}" - not a PDF file.`);
            return;
        }
        
        const reader = new FileReader();
        reader.onload = function(e) {
            const pdfData = {
                name: file.name,
                uploadedAt: new Date().toISOString(),
                uploadedBy: currentLoggedInUser,
                size: file.size,
                base64: e.target.result
            };
            
            // Check if already uploaded
            const exists = uploadedPDFs.find(pdf => pdf.name === file.name);
            if (!exists) {
                uploadedPDFs.push(pdfData);
            }
        };
        reader.readAsDataURL(file);
    });
    
    // Small delay to ensure all files are processed
    setTimeout(() => {
        saveUploadedPDFs(uploadedPDFs);
        updateUploadedPDFsList();
        fileInput.value = ''; // Clear input
        alert(`${files.length} PDF(s) uploaded successfully!`);
    }, 500);
}

// Update uploaded PDFs list UI
function updateUploadedPDFsList() {
    uploadedPDFs = loadUploadedPDFs();
    
    const countSpan = document.getElementById('pdf-count');
    const container = document.getElementById('pdf-files-container');
    const consolidateBtn = document.getElementById('consolidate-btn');
    
    countSpan.textContent = uploadedPDFs.length;
    
    if (uploadedPDFs.length === 0) {
        container.innerHTML = '<p class="info">No PDFs uploaded yet.</p>';
        consolidateBtn.disabled = true;
    } else {
        consolidateBtn.disabled = false;
        
        let html = '<div class="pdf-items">';
        uploadedPDFs.forEach((pdf, index) => {
            const uploadDate = new Date(pdf.uploadedAt).toLocaleDateString('en-US');
            const sizeKB = (pdf.size / 1024).toFixed(2);
            
            html += `
                <div class="pdf-item">
                    <div class="pdf-item-header">
                        <strong>📄 ${pdf.name}</strong>
                        <button class="remove-btn" onclick="removeUploadedPDF(${index})">✕</button>
                    </div>
                    <div class="pdf-item-details">
                        <small>Uploaded: ${uploadDate} | Size: ${sizeKB} KB</small>
                    </div>
                </div>
            `;
        });
        html += '</div>';
        container.innerHTML = html;
    }
}

// Remove uploaded PDF
function removeUploadedPDF(index) {
    const pdf = uploadedPDFs[index];
    if (confirm(`Remove "${pdf.name}"?`)) {
        uploadedPDFs.splice(index, 1);
        saveUploadedPDFs(uploadedPDFs);
        updateUploadedPDFsList();
    }
}

// Consolidate PDFs
async function consolidatePDFs() {
    if (uploadedPDFs.length === 0) {
        alert('No PDFs to consolidate!');
        return;
    }
    
    const consolidateBtn = document.getElementById('consolidate-btn');
    const resultDiv = document.getElementById('consolidation-result');
    
    consolidateBtn.disabled = true;
    consolidateBtn.textContent = '🔄 Processing PDFs...';
    resultDiv.innerHTML = '<p class="info">Extracting article data from uploaded PDFs...</p>';
    
    try {
        const allArticles = [];
        const articleFrequency = new Map();
        
        // Extract text from each PDF
        for (const pdfData of uploadedPDFs) {
            const articles = await extractArticlesFromPDF(pdfData);
            articles.forEach(article => {
                allArticles.push({
                    ...article,
                    source: pdfData.name
                });
                
                // Track frequency
                const key = article.url || article.title;
                if (articleFrequency.has(key)) {
                    const existing = articleFrequency.get(key);
                    existing.count++;
                    existing.sources.push(pdfData.name);
                } else {
                    articleFrequency.set(key, {
                        article: article,
                        count: 1,
                        sources: [pdfData.name]
                    });
                }
            });
        }
        
        // Sort by frequency (priority)
        const sortedArticles = Array.from(articleFrequency.values())
            .sort((a, b) => b.count - a.count);
        
        // Generate consolidated report
        await generateConsolidatedReport(sortedArticles, uploadedPDFs.length);
        
        resultDiv.innerHTML = `
            <div class="current">
                <h4>✅ Consolidation Complete!</h4>
                <p><strong>Total PDFs processed:</strong> ${uploadedPDFs.length}</p>
                <p><strong>Unique articles found:</strong> ${sortedArticles.length}</p>
                <p><strong>High-priority articles:</strong> ${sortedArticles.filter(a => a.count > 1).length} (appeared in multiple lists)</p>
                <p>📄 Consolidated report has been downloaded.</p>
            </div>
        `;
        
    } catch (error) {
        console.error('Error consolidating PDFs:', error);
        resultDiv.innerHTML = `
            <div class="error">
                <h4>❌ Error Processing PDFs</h4>
                <p>${error.message}</p>
                <p>Please ensure all uploaded files are valid PDFs.</p>
            </div>
        `;
    } finally {
        consolidateBtn.disabled = false;
        consolidateBtn.textContent = '🔗 Consolidate & Generate Report';
    }
}

// Extract articles from PDF
async function extractArticlesFromPDF(pdfData) {
    const pdfjsLib = window['pdfjs-dist/build/pdf'];
    pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
    
    // Convert base64 to Uint8Array
    const base64Data = pdfData.base64.split(',')[1];
    const binaryString = atob(base64Data);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    
    const pdf = await pdfjsLib.getDocument({ data: bytes }).promise;
    let fullText = '';
    
    // Extract text from all pages
    for (let i = 1; i <= pdf.numPages; i++) {
        const page = await pdf.getPage(i);
        const textContent = await page.getTextContent();
        const pageText = textContent.items.map(item => item.str).join(' ');
        fullText += pageText + '\n';
    }
    
    // Parse articles from text
    const articles = parseArticlesFromText(fullText);
    return articles;
}

// Parse articles from extracted PDF text
function parseArticlesFromText(text) {
    const articles = [];
    
    // Pattern 1: Look for numbered items with URLs
    // Example: "1. Article Title Last Updated: ... URL: https://..."
    const pattern1 = /(\d+)\.\s+([^\n]+?)\s+Last Updated:\s+([^\n]+?)\s+Age:\s+([^\n]+?)\s+URL:\s+(https?:\/\/[^\s\n]+)/gi;
    let match;
    
    while ((match = pattern1.exec(text)) !== null) {
        articles.push({
            title: match[2].trim(),
            lastUpdated: match[3].trim(),
            age: match[4].trim(),
            url: match[5].trim()
        });
    }
    
    // Pattern 2: Alternative format without numbering
    const pattern2 = /([^\n]+?)\s+Last Updated:\s+([^\n]+?)\s+Age:\s+([^\n]+?)\s+URL:\s+(https?:\/\/[^\s\n]+)/gi;
    while ((match = pattern2.exec(text)) !== null) {
        const title = match[1].trim();
        // Avoid duplicates from pattern 1
        if (!articles.find(a => a.title === title)) {
            articles.push({
                title: title,
                lastUpdated: match[2].trim(),
                age: match[3].trim(),
                url: match[4].trim()
            });
        }
    }
    
    return articles;
}

// Generate consolidated PDF report
async function generateConsolidatedReport(sortedArticles, totalPDFs) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('VWO Articles - Consolidated Priority Report', 20, 20);
    
    // Add metadata
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Generated by: ${currentLoggedInUser}`, 20, 30);
    doc.text(`Date: ${new Date().toLocaleDateString('en-US')}`, 20, 35);
    doc.text(`PDFs Consolidated: ${totalPDFs}`, 20, 40);
    doc.text(`Unique Articles: ${sortedArticles.length}`, 20, 45);
    
    // Add separator line
    doc.setLineWidth(0.5);
    doc.line(20, 50, 190, 50);
    
    let yPosition = 60;
    const pageHeight = doc.internal.pageSize.height;
    const marginBottom = 20;
    
    // Add articles sorted by priority
    sortedArticles.forEach((item, index) => {
        const article = item.article;
        
        // Check if we need a new page
        if (yPosition > pageHeight - marginBottom - 50) {
            doc.addPage();
            yPosition = 20;
        }
        
        // Priority badge
        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        const priorityText = item.count > 1 ? `🔥 PRIORITY ${item.count}x` : `${index + 1}.`;
        doc.text(priorityText, 20, yPosition);
        yPosition += 7;
        
        // Article title
        doc.setFontSize(11);
        const titleLines = doc.splitTextToSize(article.title, 160);
        doc.text(titleLines, 25, yPosition);
        yPosition += titleLines.length * 5 + 2;
        
        // Details
        doc.setFontSize(9);
        doc.setFont(undefined, 'normal');
        doc.text(`Last Updated: ${article.lastUpdated || 'N/A'}`, 25, yPosition);
        yPosition += 5;
        doc.text(`Age: ${article.age || 'N/A'}`, 25, yPosition);
        yPosition += 5;
        
        // Sources
        if (item.sources.length > 1) {
            doc.setTextColor(255, 0, 0);
            doc.text(`Appeared in ${item.count} lists: ${item.sources.join(', ')}`, 25, yPosition);
            doc.setTextColor(0, 0, 0);
            yPosition += 5;
        }
        
        // URL
        doc.setTextColor(0, 0, 255);
        const urlLines = doc.splitTextToSize(`URL: ${article.url || 'N/A'}`, 160);
        doc.text(urlLines, 25, yPosition);
        yPosition += urlLines.length * 5;
        doc.setTextColor(0, 0, 0);
        
        // Separator
        yPosition += 3;
        doc.setDrawColor(200, 200, 200);
        doc.line(20, yPosition, 190, yPosition);
        yPosition += 8;
    });
    
    // Save the PDF
    const filename = `VWO_Consolidated_Report_${new Date().getTime()}.pdf`;
    doc.save(filename);
}

// Initialize functions on page load
document.addEventListener('DOMContentLoaded', () => {
    // Check for previous login state on page load
    checkInitialLogin();
    
    // Initialize export list
    initializeExportList();
});

// Make all onclick functions globally accessible
window.loginUser = loginUser;
window.logoutUser = logoutUser;
window.checkVWOArticle = checkVWOArticle;
window.submitVWOForReview = submitVWOForReview;
window.switchTab = switchTab;
window.uploadPDFs = uploadPDFs;
window.consolidatePDFs = consolidatePDFs;
window.closeModal = closeModal;
window.reviewAction = reviewAction;
}